### ISSUE TITLE
"cubic-in-out" is undefined

### ISSUE THREAD

**Issue by t128** [pleasetrythisathome/react.animate#11]
Hi,

*react.animate* uses "cubic-in-out" as the default ease. My problem is: there is no "cubic-in-out" defined in [djdeath/ease](https://github.com/djdeath/ease/blob/master/index.js).

maybe, we should use another ease as the default.

**Comment by pleasetrythisathome** [comment]
looks like he has "in-out-cubic" that's my bad for accepting his replacement of  d3 easing without confirming api consistency...
